FROM ubuntu:20.04
RUN apt-get update
RUN apt-get install build-essential git -y
RUN apt-get install python3 python3-dev python3-venv python3-pip python3-wheel -y
RUN python3 -m pip install numpy requests tqdm
